global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "hos-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:3000"]

  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "alertmanager"
    metrics_path: /metrics
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "postgres"
    metrics_path: /metrics
    static_configs:
      - targets: ["postgres-exporter:9187"]


